# Generated by Django 6.0.6 on 2026-10-06 10:45

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0036_companyinvoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinvoice',
            name='truck_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='companyinvoice',
            name='trailer_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='companyinvoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinvoice',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_invoices_paid', to=settings.AUTH_USER_MODEL),
        ),
    ]
